"""Add role to users

Revision ID: 4a6356381a46
Revises: 125ba6056c73
Create Date: 2026-06-12 14:10:36.968388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6356381a46'
down_revision: Union[str, Sequence[str], None] = '125ba6056c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('urls', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('urls', 'notes')
    op.drop_column('urls', 'is_active')
    # ### end Alembic commands ###
